apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: elasticsearch-hap
  namespace: systems-dev-ns
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: elasticsearch-node
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
