apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: systems-dev-ns
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
data:
  fluent.conf: |
    #@include systemd.conf
    @include kubernetes.conf
    @include kubernetes2.conf
    <match **>
      @type elasticsearch
      @id out_es
      @log_level info
      include_tag_key true
      host elasticsearch-node.systems-dev-ns.svc.cluster.local
      port 9200
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'false'}"
      reoload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'true'}"
      logstash_prefix "#{ENV['FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX'] || 'logstash'}"
      logstash_format true
      type_name fluentd
      buffer_chunk_limit 2M
      buffer_queue_limit 32
      flush_interval 5s
      max_retry_wait 30
      disable_retry_limit
      num_threads 8
    </match>
  kubernetes.conf: |
    <match fluent.**>
       @type null
    </match>
    <source>
       @type tail
       @id in_tail_container_logs
       path /app/logs/spring.log
       pos_file /app/logs/fluentd-containers.log.pos
       tag *
       read_from_head true
       <parse>
         @type regexp
         expression /^\[(?<logtime>[^\]]*)\]\[(?<thread_name>[^\]]*)\] (?<log_level>[^ ]*) (?<logger_name>[^ ]*[^  ]*)  - (?<log_text>.*)$/
         time_format "%Y-%m-%d %H:%M:%S.%3N"
         time_type string
       </parse>
    </source>
